### Get all tasks
GET http://localhost:4000/tasks
Content-Type: application/json

### Get task by ID
GET http://localhost:4000/tasks/1
Content-Type: application/json

### Create new task
POST http://localhost:4000/tasks
Content-Type: application/json

{
  "title": "Review urgent application",
  "description": "Check eligibility and verify documents",
  "status": "OPEN",
  "dueDateTime": "2025-11-23T12:30"
}

### Update existing task
PUT http://localhost:4000/tasks/24
Content-Type: application/json

{
  "id": 24,
  "title": "Review urgent application",
  "description": "Check eligibility and verify documents",
  "status": "IN_PROGRESS",
  "dueDateTime": "2025-10-17T17:30"
}

### Delete an existing task
DELETE http://localhost:4000/tasks/24
Content-Type: application/json

### Create new task (invalid data)
POST http://localhost:4000/tasks
Content-Type: application/json

{
  "title": "",
  "description": "This entry is invalid as the title is empty",
  "status": "OPEN",
  "dueDateTime": "2025-09-17T12:30"
}


